
import "./globals.css";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],
});

export const metadata = {
  title: "Harmony Chain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">

      <body className={`min-h-screen ${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
